language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
services:
  - postgresql
script:
  — bundle install — jobs=3 — retry=3
  — bundle exec rake db:create
  — bundle exec rake db:migrate
  — bundle exec rspec