language: ruby
rbenv:
  - 2.7.2
services:
  - postgresql
before_install:
  - gem install bundler -v '2.2.28'
before_script:
  - bundle install
  - bundle exec rails db:reset
script: 
  - bundle exec rspec